# Week 5 - Wed Lab (09/30/26) 

This code accompanies activities for the 09/30/26 lab.

**Table of Contents**

1. [Plicker Questions Code](#sec1)
2. [Cosine Similarity Whiteboard Activity - Your Task](#sec2)
3. [Wikipedia country-specific data](#sec3)

<a id="sec1"></a>
## 1. Plicker Questions Code

This code relates to the Question 13 on the Plicker set of questions for today. We will run the code line by line to see what is going on.

In [2]:
from datetime import datetime, timedelta

**Create a new datetime object**

In [3]:
date1 = datetime(2023, 5, 1)
type(date1)

datetime.datetime

**Create a new timedelta object**

In [4]:
delta = timedelta(days=10)
type(delta)

datetime.timedelta

In [5]:
print(delta)

10 days, 0:00:00

**Adding the two objects**

In [6]:
date2 = date1 + delta
print(date2)

2023-05-11 00:00:00

**Why is this possible?**

Let's show all methods / properties of the object:

In [7]:
dir(date1)

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__replace__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'astimezone',
 'combine',
 'ctime',
 'date',
 'day',
 'dst',
 'fold',
 'fromisocalendar',
 'fromisoformat',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'microsecond',
 'min',
 'minute',
 'month',
 'now',
 'replace',
 'resolution',
 'second',
 'strftime',
 'strptime',
 'time',
 'timestamp',
 'timetuple',
 'timetz',
 'today',
 'toordinal',
 'tzinfo',
 'tzname',
 'utcfromtimestamp',
 'utcnow',
 'utcoffset',
 'utctimetuple',
 'weekday',
 'year']

Let's look up the docstring of the method `__add__`, which is what is called when we use the + operator:

In [8]:
help(date1.__add__)

Help on method-wrapper:

__add__(value, /) unbound datetime.datetime method
    Return self+value.

**Conclusion:** There is a class method that will accept any value type and then act accordingly to figure out how to add that value to the date, if possible.

<a id="sec2"></a>
## 2. Cosine Similarity Whiteboard Activity

This activity was completed by hand, here is how to do it via Python code.

### Inputs for the problem

In [9]:
documents = [
    "Max likes Sam.",    # D1
    "Sam likes Max.",    # D2
    "Max and Sam.",      # D3
    "Winter likes fall." # D4
]

query = "Sam likes winter"

### Step 1: Create vocabulary of all terms

First I will concatenate all strings into one.

In [10]:
allText = " ".join(documents + [query])
print(allText)

Max likes Sam. Sam likes Max. Max and Sam. Winter likes fall. Sam likes winter

I don't want to have punctuation. There are several ways to do that. Let's see some:

#### Method 1: Iterate over the string, leave out punctuations

In [ ]:
import string
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [12]:
allText_noPunct = "".join([ch for ch in allText if not ch in string.punctuation])
print(allText_noPunct)

Max likes Sam Sam likes Max Max and Sam Winter likes fall Sam likes winter

### Method 2: Use built-in methods

Pythyn's built-in `str` class has many useful methods for translating a set of characters to another one. Let's see the method in action:

In [13]:
allText.translate(str.maketrans("", "", string.punctuation))

'Max likes Sam Sam likes Max Max and Sam Winter likes fall Sam likes winter'

What's going on?

In [14]:
print(str.maketrans("", "", string.punctuation))

{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}

We can see that all ASCII Characters from 0-32 and from 65 to 90 are missing, because those characters will be deleted.

Here is what is happening:

```
str.maketrans(from_str, to_str, delete_chars)
#              ^          ^        ^
#           1st arg    2nd arg  3rd arg
```

* 1st argument (""): The characters you want to replace. (Empty string = replace nothing)

* 2nd argument (""): The characters to replace them with. (Empty string = no replacement mapping)

* 3rd argument (string.punctuation): The characters you want to delete entirely.

### Our vocabulary

Here is a Python one-liner that takes our variable `allText_noPunct` and find the unique words in it.

In [15]:
words = set(allText_noPunct.lower().split())
words

{'and', 'fall', 'likes', 'max', 'sam', 'winter'}

In [16]:
voc = sorted(words)
voc

['and', 'fall', 'likes', 'max', 'sam', 'winter']

### YOUR TURN

Write code to implement the other steps of the process shown in Slide 7.

**Show your process before writing any functions.**

**Use markdown to label the three remaining steps.**

### Step 2: Represent each document and the query in the vector space created by these terms

#### A. Clean the documents

In [22]:
clean_doc = []

for doc in documents:
    doc_noPunct = "".join([ch for ch in doc if not ch in string.punctuation])
    clean_doc.append(doc_noPunct.lower().split())

print(clean_doc)

[['max', 'likes', 'sam'], ['sam', 'likes', 'max'], ['max', 'and', 'sam'], ['winter', 'likes', 'fall']]

#### B. Create the Vectors

In [27]:
vectors = []
for i in range(len(clean_doc)):
    vector = []
    for word in voc:
        vector.append(clean_doc[i].count(word))
    vectors.append(vector)


print(vectors)

[[0, 0, 1, 1, 1, 0], [0, 0, 1, 1, 1, 0], [1, 0, 0, 1, 1, 0], [0, 1, 1, 0, 0, 1]]

##### Create the query vector

In [28]:
query_vector = []
for word in voc:
    query_vector.append(query.lower().split().count(word))

print(query_vector)

[0, 0, 1, 0, 1, 1]

### Step 3: Calculate the cosine similarity between the query and each document

#### A. Define the cosine similarity formula

In [31]:
import numpy as np
from numpy.linalg import norm

def cosineSimilarity(vec1, vec2):
    v1 = np.array(vec1)
    v2 = np.array(vec2)
    cosine = np.dot(v1, v2) / (norm(v1) * norm(v2))
    return cosine

#### B. Calculate the cosine similarity

In [32]:
similarities = []
for vector in vectors:
    similarities.append(cosineSimilarity(vector, query_vector))

print(similarities)

[np.float64(0.6666666666666667), np.float64(0.6666666666666667), np.float64(0.33333333333333337), np.float64(0.6666666666666667)]

### Step 4:  Rank the results based on the cosine similarity

In [40]:
sorted_ind = np.argsort(similarities)[::-1] # Find the indices of the sorted similarities in descending order

for i in sorted_ind:
    print("D"+str(i)+":", documents[i], ":", round(similarities[i],3))

D3: Winter likes fall. : 0.667
D1: Sam likes Max. : 0.667
D0: Max likes Sam. : 0.667
D2: Max and Sam. : 0.333

<a id="sec3"></a>
## 3. Wikipedia Country-Specific Data

If we know the URL of a date, for example:

```
https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-29.tsv
```

we can use pandas to read the content of the file into a dataframe.

In [20]:
import pandas as pd

url = "https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-29.tsv"

df = pd.read_csv(url, sep='\t')

df.head()

HTTPError: HTTP Error 403: Forbidden

Why did this happen? Wikimedia didn't like that we didn't identify ourselves. This is why we need to first get data with requests, then read it from pandas.

In [21]:
import pandas as pd
import requests, io

url = "https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-29.tsv"

headers = {'User-Agent': 'MyDataAnalysisScript/1.0 (contact: wendywellesley@gmail.com)'}
response = requests.get(url, headers=headers)

df = pd.read_csv(io.StringIO(response.text), sep='\t')
df.head()

     Algeria  DZ  ar.wikipedia     3947 Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù    Q11660  122
0  Argentina  AR  es.wikipedia  3094323             Juana_Viale  Q9016209  115
1  Argentina  AR  es.wikipedia   327209          JosÃ©_Mourinho    Q79983  114
2  Argentina  AR  es.wikipedia  4449701       Copa_Libertadores   Q184795  386
3  Argentina  AR  es.wikipedia    47340          Thomas_Sankara   Q202155  119
4  Argentina  AR  es.wikipedia  5640452         Michael_Jackson     Q2831  177

The dataframe doesn't have column name. 

**Your task:** Read the README file to find out the column names and add them to the dataframe.

#### Create a Python list containing the names as strings

In [45]:
columns = ['country', 'project', 'page_id', 'page_title', 'item_id', 'gbc']

#### Update pd.read_csv() with update name as argument

In [48]:
df =pd.read_csv(io.StringIO(response.text), header=None, names=columns,sep='\t')

In [50]:
df.head()

,country,project,page_id,page_title,item_id,gbc
Algeria,DZ,ar.wikipedia,3947,Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù,Q11660,122
Argentina,AR,es.wikipedia,3094323,Juana_Viale,Q9016209,115
Argentina,AR,es.wikipedia,327209,JosÃ©_Mourinho,Q79983,114
Argentina,AR,es.wikipedia,4449701,Copa_Libertadores,Q184795,386
Argentina,AR,es.wikipedia,47340,Thomas_Sankara,Q202155,119

The README file did not mention country code. I could manually add it as a column name:

In [59]:
columns = ['country','country_code', 'project', 'page_id', 'page_title', 'item_id', 'gbc']
df =pd.read_csv(io.StringIO(response.text), header=None, names=columns,sep='\t')
df.head()

,country,country_code,project,page_id,page_title,item_id,gbc
0,Algeria,DZ,ar.wikipedia,3947,Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù,Q11660,122
1,Argentina,AR,es.wikipedia,3094323,Juana_Viale,Q9016209,115
2,Argentina,AR,es.wikipedia,327209,JosÃ©_Mourinho,Q79983,114
3,Argentina,AR,es.wikipedia,4449701,Copa_Libertadores,Q184795,386
4,Argentina,AR,es.wikipedia,47340,Thomas_Sankara,Q202155,119

### Task 3

#### 1. Manually choose 10 recent, highly rated shows from MyDramaList


1. Teach You a Lesson	9.0
2. Four Hands, Two Sonatas	8.7
3. Bloodhounds Season 2	8.7
4. Agent Kim Reactivated	8.6
5. Yumi’s Cells Season 3	8.6
6. We Are All Trying Here	8.5
7. A Shop for Killers Season 2	8.5
8. The WONDERfools	8.5
9. The Legend of Kitchen Soldier	8.5
10. A Bona Fide Killer	8.4

#### 2. Find each show's Wiki article name

Limitation: There are some wikipedia page that is the whole-series article.

In [60]:
articles = [
    "Teach_You_a_Lesson",
    "Four_Hands,_Two_Sonatas",
    "Bloodhounds_(TV_series)",
    "Agent_Kim_Reactivated",
    "Yumi's_Cells",
    "We_Are_All_Trying_Here",
    "A_Shop_for_Killers",
    "The_Wonderfools",
    "The_Legend_of_Kitchen_Soldier",
    "A_Bona_Fide_Killer"
]

#### 3. Collect matching pageview rows for all 30 days of September

create `dates` to represent all days in september

In [65]:
dates = pd.date_range(
    start="2026-09-01",
    end="2026-09-30"
).strftime("%Y-%m-%d")

Loop through each date

In [70]:
daily_data= []

for date in dates:
    url = f"https://analytics.wikimedia.org/published/datasets/country_project_page/{date}.tsv"
    response = requests.get(url, headers=headers)
    df = pd.read_csv(io.StringIO(response.text), header=None, names=columns, sep='\t')
    filtered_df = df[df['page_title'].isin(articles)]
    daily_data.append(filtered_df)

print(daily_data)

[              country country_code       project   page_id  \
4994         Malaysia           MY  en.wikipedia  75697706
5051        Singapore           SG  en.wikipedia  79560156
7530          Germany           DE  de.wikipedia  13931524
7726        Indonesia           ID  id.wikipedia   4750411
8729    United States           US  en.wikipedia  79560156
...               ...          ...           ...       ...
260476          Japan           JP  en.wikipedia  82034667
278268          India           IN  en.wikipedia  73002553
279446      Australia           AU  en.wikipedia  82034667
282870          India           IN  en.wikipedia  82003107
284132         Canada           CA  en.wikipedia  82034667

                     page_title     item_id  gbc
4994         A_Shop_for_Killers  Q123999260  160
5051         Teach_You_a_Lesson  Q137844128  129
7530    Four_Hands,_Two_Sonatas  Q137271520  236
7726         A_Bona_Fide_Killer  Q139411314  247
8729         Teach_You_a_Lesson  Q137844128  577
...                         ...         ...  ...
260476  Four_Hands,_Two_Sonatas  Q137271520  150
278268  Bloodhounds_(TV_series)  Q109767798  101
279446  Four_Hands,_Two_Sonatas  Q137271520  203
282870    Agent_Kim_Reactivated  Q139553270  210
284132  Four_Hands,_Two_Sonatas  Q137271520  279

[63 rows x 7 columns],                country country_code       project   page_id  \
4964          Malaysia           MY  en.wikipedia  75697706
5023         Singapore           SG  en.wikipedia  79560156
7489           Germany           DE  de.wikipedia  13931524
7684         Indonesia           ID  id.wikipedia   4750411
8682     United States           US  en.wikipedia  79560156
12050            India           IN  en.wikipedia  82034667
12285          Nigeria           NG  en.wikipedia  83488921
14643        Australia           AU  en.wikipedia  79560156
21216         Malaysia           MY  en.wikipedia  82034667
26822            India           IN  en.wikipedia  78258360
27290   United Kingdom           GB  en.wikipedia  79560156
38773            India           IN  en.wikipedia  79560156
45254   United Kingdom           GB  en.wikipedia  82034667
51005      Philippines           PH  en.wikipedia  82003107
63981           France           FR  fr.wikipedia  17588331
68295        Australia           AU  en.wikipedia  82003107
74963      Philippines           PH  en.wikipedia  82034667
76186        Indonesia           ID  en.wikipedia  79560156
79453      Philippines           PH  en.wikipedia  83488921
88429      Philippines           PH  en.wikipedia  79560156
92637        Indonesia           ID  id.wikipedia   4694064
94397        Singapore           SG  en.wikipedia  82003107
97313         Malaysia           MY  en.wikipedia  82003107
102521   United States           US  en.wikipedia  82003107
113520           Italy           IT  en.wikipedia  82034667
116231          Canada           CA  en.wikipedia  79560156
120658          France           FR  fr.wikipedia  17514844
125145          Canada           CA  en.wikipedia  82003107
126895       Indonesia           ID  en.wikipedia  82003107
128322       Indonesia           ID  id.wikipedia   4680537
131260       Indonesia           ID  en.wikipedia  83488921
134141       Indonesia           ID  id.wikipedia   4737177
136662   United States           US  en.wikipedia  78258360
164899   United States           US  en.wikipedia  75697706
168600     Philippines           PH  en.wikipedia  75697706
173864   United States           US  en.wikipedia  82034667
175835           India           IN  en.wikipedia  83488921
178404   United States           US  en.wikipedia  82159028
178836           India           IN  en.wikipedia  75697706
181496          Brazil           BR  en.wikipedia  82034667
187796       Indonesia           ID  en.wikipedia  82034667
193817        Malaysia           MY  en.wikipedia  79560156
193878       Singapore           SG  en.wikipedia  75697706
198144        Malaysia           MY  en.wikipedia  83488921
204968   United States           US  en.wikipedia  73002553
234020       Singapore           SG  en.wikipedia  83488921
235335           Japan           JP  en.wikipedia  82003107
239356   United States           US  en.wikipedia  83488921
253283           India           IN  en.wikipedia  81854574
259219           Japan           JP  en.wikipedia  82034667
276884           India           IN  en.wikipedia  73002553
278043       Australia           AU  en.wikipedia  82034667
281452           India           IN  en.wikipedia  82003107
282712          Canada           CA  en.wikipedia  82034667

                           page_title     item_id  gbc
4964               A_Shop_for_Killers  Q123999260  105
5023               Teach_You_a_Lesson  Q137844128  104
7489          Four_Hands,_Two_Sonatas  Q137271520  144
7684               A_Bona_Fide_Killer  Q139411314  276
8682               Teach_You_a_Lesson  Q137844128  485
12050         Four_Hands,_Two_Sonatas  Q137271520  649
12285              A_Bona_Fide_Killer  Q139411314  110
14643              Teach_You_a_Lesson  Q137844128   90
21216         Four_Hands,_Two_Sonatas  Q137271520  301
26822                 The_Wonderfools  Q130748503  155
27290              Teach_You_a_Lesson  Q137844128   93
38773              Teach_You_a_Lesson  Q137844128  405
45254         Four_Hands,_Two_Sonatas  Q137271520  159
51005           Agent_Kim_Reactivated  Q139553270  176
63981         Four_Hands,_Two_Sonatas         NaN  152
68295           Agent_Kim_Reactivated  Q139553270  120
74963         Four_Hands,_Two_Sonatas  Q137271520  429
76186              Teach_You_a_Lesson  Q137844128  103
79453              A_Bona_Fide_Killer  Q139411314  381
88429              Teach_You_a_Lesson  Q137844128  160
92637         Four_Hands,_Two_Sonatas  Q137271520  456
94397           Agent_Kim_Reactivated  Q139553270  178
97313           Agent_Kim_Reactivated  Q139553270  153
102521          Agent_Kim_Reactivated  Q139553270  547
113520        Four_Hands,_Two_Sonatas  Q137271520  138
116231             Teach_You_a_Lesson  Q137844128  112
120658          Agent_Kim_Reactivated  Q139553270  135
125145          Agent_Kim_Reactivated  Q139553270  111
126895          Agent_Kim_Reactivated  Q139553270  136
128322             Teach_You_a_Lesson  Q137844128  104
131260             A_Bona_Fide_Killer  Q139411314  139
134141          Agent_Kim_Reactivated  Q139553270  235
136662                The_Wonderfools  Q130748503  183
164899             A_Shop_for_Killers  Q123999260  313
168600             A_Shop_for_Killers  Q123999260  179
173864        Four_Hands,_Two_Sonatas  Q137271520  903
175835             A_Bona_Fide_Killer  Q139411314  229
178404         We_Are_All_Trying_Here  Q137843064   96
178836             A_Shop_for_Killers  Q123999260  231
181496        Four_Hands,_Two_Sonatas  Q137271520  135
187796        Four_Hands,_Two_Sonatas  Q137271520  157
193817             Teach_You_a_Lesson  Q137844128  116
193878             A_Shop_for_Killers  Q123999260  109
198144             A_Bona_Fide_Killer  Q139411314  257
204968        Bloodhounds_(TV_series)  Q109767798  124
234020             A_Bona_Fide_Killer  Q139411314  156
235335          Agent_Kim_Reactivated  Q139553270  215
239356             A_Bona_Fide_Killer  Q139411314  363
253283  The_Legend_of_Kitchen_Soldier  Q137410939  233
259219        Four_Hands,_Two_Sonatas  Q137271520  110
276884        Bloodhounds_(TV_series)  Q109767798  144
278043        Four_Hands,_Two_Sonatas  Q137271520  167
281452          Agent_Kim_Reactivated  Q139553270  338
282712        Four_Hands,_Two_Sonatas  Q137271520  195  ,                country country_code       project   page_id  \
5024          Malaysia           MY  en.wikipedia  75697706
5080         Singapore           SG  en.wikipedia  79560156
7529           Germany           DE  de.wikipedia  13931524
7715         Indonesia           ID  id.wikipedia   4750411
8711     United States           US  en.wikipedia  79560156
12134            India           IN  en.wikipedia  82034667
14768        Australia           AU  en.wikipedia  79560156
21275         Malaysia           MY  en.wikipedia  82034667
26942            India           IN  en.wikipedia  78258360
27406   United Kingdom           GB  en.wikipedia  79560156
38878            India           IN  en.wikipedia  79560156
45378   United Kingdom           GB  en.wikipedia  82034667
51210      Philippines           PH  en.wikipedia  82003107
64214           France           FR  fr.wikipedia  17588331
75199      Philippines           PH  en.wikipedia  82034667
76468        Indonesia           ID  en.wikipedia  79560156
79686      Philippines           PH  en.wikipedia  83488921
88584      Philippines           PH  en.wikipedia  79560156
92789        Indonesia           ID  id.wikipedia   4694064
94558        Singapore           SG  en.wikipedia  82003107
97512         Malaysia           MY  en.wikipedia  82003107
102717   United States           US  en.wikipedia  82003107
107271   United States           US  en.wikipedia  81854574
113779           Italy           IT  en.wikipedia  82034667
116474          Canada           CA  en.wikipedia  79560156
120968          France           FR  fr.wikipedia  17514844
125403          Canada           CA  en.wikipedia  82003107
127167       Indonesia           ID  en.wikipedia  82003107
128600       Indonesia           ID  id.wikipedia   4680537
131560       Indonesia           ID  en.wikipedia  83488921
134521       Indonesia           ID  id.wikipedia   4737177
137039   United States           US  en.wikipedia  78258360
165269   United States           US  en.wikipedia  75697706
168966     Philippines           PH  en.wikipedia  75697706
173045         Germany           DE  en.wikipedia  79560156
174180   United States           US  en.wikipedia  82034667
176121           India           IN  en.wikipedia  83488921
178712   United States           US  en.wikipedia  82159028
179167           India           IN  en.wikipedia  75697706
188217       Indonesia           ID  en.wikipedia  82034667
194270        Malaysia           MY  en.wikipedia  79560156
194331       Singapore           SG  en.wikipedia  75697706
198589        Malaysia           MY  en.wikipedia  83488921
199583       Australia           AU  en.wikipedia  83488921
205410   United States           US  en.wikipedia  73002553
234612       Singapore           SG  en.wikipedia  83488921
235932           Japan           JP  en.wikipedia  82003107
239895   United States           US  en.wikipedia  83488921
246019         Germany           DE  de.wikipedia  13892974
253717           India           IN  en.wikipedia  81854574
277343           India           IN  en.wikipedia  73002553
278486       Australia           AU  en.wikipedia  82034667
281922           India           IN  en.wikipedia  82003107
283190          Canada           CA  en.wikipedia  82034667

                           page_title     item_id  gbc
5024               A_Shop_for_Killers  Q123999260  147
5080               Teach_You_a_Lesson  Q137844128  129
7529          Four_Hands,_Two_Sonatas  Q137271520  155
7715               A_Bona_Fide_Killer  Q139411314  275
8711               Teach_You_a_Lesson  Q137844128  453
12134         Four_Hands,_Two_Sonatas  Q137271520  561
14768              Teach_You_a_Lesson  Q137844128   99
21275         Four_Hands,_Two_Sonatas  Q137271520  191
26942                 The_Wonderfools  Q130748503  140
27406              Teach_You_a_Lesson  Q137844128  136
38878              Teach_You_a_Lesson  Q137844128  394
45378         Four_Hands,_Two_Sonatas  Q137271520  164
51210           Agent_Kim_Reactivated  Q139553270  160
64214         Four_Hands,_Two_Sonatas         NaN  123
75199         Four_Hands,_Two_Sonatas  Q137271520  365
76468              Teach_You_a_Lesson  Q137844128  134
79686              A_Bona_Fide_Killer  Q139411314  346
88584              Teach_You_a_Lesson  Q137844128  187
92789         Four_Hands,_Two_Sonatas  Q137271520  436
94558           Agent_Kim_Reactivated  Q139553270  189
97512           Agent_Kim_Reactivated  Q139553270  146
102717          Agent_Kim_Reactivated  Q139553270  463
107271  The_Legend_of_Kitchen_Soldier  Q137410939  124
113779        Four_Hands,_Two_Sonatas  Q137271520  100
116474             Teach_You_a_Lesson  Q137844128  132
120968          Agent_Kim_Reactivated  Q139553270  138
125403          Agent_Kim_Reactivated  Q139553270  113
127167          Agent_Kim_Reactivated  Q139553270  121
128600             Teach_You_a_Lesson  Q137844128  161
131560             A_Bona_Fide_Killer  Q139411314  111
134521          Agent_Kim_Reactivated  Q139553270  179
137039                The_Wonderfools  Q130748503  235
165269             A_Shop_for_Killers  Q123999260  219
168966             A_Shop_for_Killers  Q123999260  169
173045             Teach_You_a_Lesson  Q137844128  105
174180        Four_Hands,_Two_Sonatas  Q137271520  755
176121             A_Bona_Fide_Killer  Q139411314  209
178712         We_Are_All_Trying_Here  Q137843064  128
179167             A_Shop_for_Killers  Q123999260  255
188217        Four_Hands,_Two_Sonatas  Q137271520  200
194270             Teach_You_a_Lesson  Q137844128  131
194331             A_Shop_for_Killers  Q123999260  100
198589             A_Bona_Fide_Killer  Q139411314  309
199583             A_Bona_Fide_Killer  Q139411314  106
205410        Bloodhounds_(TV_series)  Q109767798  149
234612             A_Bona_Fide_Killer  Q139411314  119
235932          Agent_Kim_Reactivated  Q139553270  244
239895             A_Bona_Fide_Killer  Q139411314  285
246019          Agent_Kim_Reactivated  Q139553270   99
253717  The_Legend_of_Kitchen_Soldier  Q137410939  350
277343        Bloodhounds_(TV_series)  Q109767798  136
278486        Four_Hands,_Two_Sonatas  Q137271520  165
281922          Agent_Kim_Reactivated  Q139553270  343
283190        Four_Hands,_Two_Sonatas  Q137271520  217  ,                country country_code       project   page_id  \
5140          Malaysia           MY  en.wikipedia  75697706
5194         Singapore           SG  en.wikipedia  79560156
7719           Germany           DE  de.wikipedia  13931524
7918         Indonesia           ID  id.wikipedia   4750411
8906     United States           US  en.wikipedia  79560156
12398            India           IN  en.wikipedia  82034667
15019        Australia           AU  en.wikipedia  79560156
21629         Malaysia           MY  en.wikipedia  82034667
27418            India           IN  en.wikipedia  78258360
27894   United Kingdom           GB  en.wikipedia  79560156
39489            India           IN  en.wikipedia  79560156
46091   United Kingdom           GB  en.wikipedia  82034667
51951      Philippines           PH  en.wikipedia  82003107
76194      Philippines           PH  en.wikipedia  82034667
77447        Indonesia           ID  en.wikipedia  79560156
80730      Philippines           PH  en.wikipedia  83488921
89781      Philippines           PH  en.wikipedia  79560156
94023        Indonesia           ID  id.wikipedia   4694064
95827        Singapore           SG  en.wikipedia  82003107
98812         Malaysia           MY  en.wikipedia  82003107
104082   United States           US  en.wikipedia  82003107
115376           Italy           IT  en.wikipedia  82034667
120468  United Kingdom           GB  en.wikipedia  82003107
122674          France           FR  fr.wikipedia  17514844
128997       Indonesia           ID  en.wikipedia  82003107
130426       Indonesia           ID  id.wikipedia   4680537
133479       Indonesia           ID  en.wikipedia  83488921
136421       Indonesia           ID  id.wikipedia   4737177
138931   United States           US  en.wikipedia  78258360
167663   United States           US  en.wikipedia  75697706
171427     Philippines           PH  en.wikipedia  75697706
175624         Germany           DE  en.wikipedia  79560156
176775   United States           US  en.wikipedia  82034667
178766           India           IN  en.wikipedia  83488921
181784           India           IN  en.wikipedia  75697706
190866       Indonesia           ID  en.wikipedia  82034667
196942        Malaysia           MY  en.wikipedia  79560156
200883          Canada           CA  en.wikipedia  83488921
201360        Malaysia           MY  en.wikipedia  83488921
208304   United States           US  en.wikipedia  73002553
215041           Japan           JP  en.wikipedia  75697706
238055       Singapore           SG  en.wikipedia  83488921
239381           Japan           JP  en.wikipedia  82003107
243411   United States           US  en.wikipedia  83488921
257170          France           FR  en.wikipedia  83488921
257426           India           IN  en.wikipedia  81854574
263447           Japan           JP  en.wikipedia  82034667
281393           India           IN  en.wikipedia  73002553
282570       Australia           AU  en.wikipedia  82034667
286022           India           IN  en.wikipedia  82003107
287285          Canada           CA  en.wikipedia  82034667

                           page_title     item_id  gbc
5140               A_Shop_for_Killers  Q123999260  126
5194               Teach_You_a_Lesson  Q137844128  126
7719          Four_Hands,_Two_Sonatas  Q137271520  163
7918               A_Bona_Fide_Killer  Q139411314  420
8906               Teach_You_a_Lesson  Q137844128  523
12398         Four_Hands,_Two_Sonatas  Q137271520  397
15019              Teach_You_a_Lesson  Q137844128  135
21629         Four_Hands,_Two_Sonatas  Q137271520  206
27418                 The_Wonderfools  Q130748503  148
27894              Teach_You_a_Lesson  Q137844128  134
39489              Teach_You_a_Lesson  Q137844128  648
46091         Four_Hands,_Two_Sonatas  Q137271520  122
51951           Agent_Kim_Reactivated  Q139553270  202
76194         Four_Hands,_Two_Sonatas  Q137271520  301
77447              Teach_You_a_Lesson  Q137844128  101
80730              A_Bona_Fide_Killer  Q139411314  536
89781              Teach_You_a_Lesson  Q137844128  180
94023         Four_Hands,_Two_Sonatas  Q137271520  295
95827           Agent_Kim_Reactivated  Q139553270  199
98812           Agent_Kim_Reactivated  Q139553270  150
104082          Agent_Kim_Reactivated  Q139553270  483
115376        Four_Hands,_Two_Sonatas  Q137271520  103
120468          Agent_Kim_Reactivated  Q139553270   96
122674          Agent_Kim_Reactivated  Q139553270  137
128997          Agent_Kim_Reactivated  Q139553270  114
130426             Teach_You_a_Lesson  Q137844128  182
133479             A_Bona_Fide_Killer  Q139411314  172
136421          Agent_Kim_Reactivated  Q139553270  241
138931                The_Wonderfools  Q130748503  230
167663             A_Shop_for_Killers  Q123999260  222
171427             A_Shop_for_Killers  Q123999260  156
175624             Teach_You_a_Lesson  Q137844128  124
176775        Four_Hands,_Two_Sonatas  Q137271520  762
178766             A_Bona_Fide_Killer  Q139411314  367
181784             A_Shop_for_Killers  Q123999260  203
190866        Four_Hands,_Two_Sonatas  Q137271520  121
196942             Teach_You_a_Lesson  Q137844128  158
200883             A_Bona_Fide_Killer  Q139411314  100
201360             A_Bona_Fide_Killer  Q139411314  324
208304        Bloodhounds_(TV_series)  Q109767798  157
215041             A_Shop_for_Killers  Q123999260   90
238055             A_Bona_Fide_Killer  Q139411314  247
239381          Agent_Kim_Reactivated  Q139553270  268
243411             A_Bona_Fide_Killer  Q139411314  457
257170             A_Bona_Fide_Killer  Q139411314   98
257426  The_Legend_of_Kitchen_Soldier  Q137410939  273
263447        Four_Hands,_Two_Sonatas  Q137271520  126
281393        Bloodhounds_(TV_series)  Q109767798  138
282570        Four_Hands,_Two_Sonatas  Q137271520  168
286022          Agent_Kim_Reactivated  Q139553270  384

Combine the daily tables

In [72]:
for date,data in zip(dates, daily_data):
    data['date'] = date

september_df = pd.concat(daily_data, ignore_index=True)
september_df

,country,country_code,project,page_id,page_title,item_id,gbc,date
0,Malaysia,MY,en.wikipedia,75697706,A_Shop_for_Killers,Q123999260,160,2026-09-01
1,Singapore,SG,en.wikipedia,79560156,Teach_You_a_Lesson,Q137844128,129,2026-09-01
2,Germany,DE,de.wikipedia,13931524,"Four_Hands,_Two_Sonatas",Q137271520,236,2026-09-01
3,Indonesia,ID,id.wikipedia,4750411,A_Bona_Fide_Killer,Q139411314,247,2026-09-01
4,United States,US,en.wikipedia,79560156,Teach_You_a_Lesson,Q137844128,577,2026-09-01
...,...,...,...,...,...,...,...,...
1428,Japan,JP,en.wikipedia,82034667,"Four_Hands,_Two_Sonatas",Q137271520,134,2026-09-30
1429,India,IN,en.wikipedia,73002553,Bloodhounds_(TV_series),Q109767798,121,2026-09-30
1430,Australia,AU,en.wikipedia,82034667,"Four_Hands,_Two_Sonatas",Q137271520,102,2026-09-30
1431,India,IN,en.wikipedia,82003107,Agent_Kim_Reactivated,Q139553270,168,2026-09-30
1432,Canada,CA,en.wikipedia,82034667,"Four_Hands,_Two_Sonatas",Q137271520,135,2026-09-30

#### 4. Save those rows as a CSV or TSV.

In [73]:
september_df.to_csv("sep_page.csv", index=False)

#### 5. visualization